<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeDirectory.Core\EmployeeDirectory.Core.csproj" />
    <ProjectReference Include="..\EmployeeDirectory.ServiceDefaults\EmployeeDirectory.ServiceDefaults.csproj" />
    <ProjectReference Include="..\EmployeeDirectory.UI\EmployeeDirectory.UI.csproj" />
  </ItemGroup>

</Project>
