// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using EmployeeDirectory.Core.Enums;

namespace EmployeeDirectory.Core.Models;

public partial class Location
{
    [Column("Id")]
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string? LocName { get; set; }

    [Required]
    public int? LocNum { get; set; }

    [Required]
    public string? Address { get; set; }

    [Required]
    public string? City { get; set; }

    [Required]
    [StringLength(3)]
    public string? State { get; set; }

    [Required]
    [Column(TypeName = "TEXT")]
    public string? Zipcode { get; set; }

    [StringLength(15)]
    [Phone]
    public string? PhoneNumber { get; set; }

    [StringLength(15)]
    [Phone]
    public string? FaxNumber { get; set; }

    [StringLength(15)]
    [Phone]
    public string? AltNumber { get; set; }

    [Column("Email")]
    [EmailAddress]
    [StringLength(60)]
    public string? Email { get; set; }

    public string? Hours { get; set; }

    [Required]
    public Loctype Loctype { get; set; }

    public string? AreaManager { get; set; }

    public string? StoreManager { get; set; }

    [JsonIgnore]
    public DateTime? RecordAdd { get; set; }

    
    public bool? Active { get; set; } = true;

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    //public virtual Loctype? LocationType { get; set; }
}